apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: service  
  name: my-service
spec:
  ports:
  - nodePort: 31111
    port: 9001
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-ns
  type: NodePort
status:
  loadBalancer: {}
