apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: febe 
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: be 
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: fe
    ports:
    - protocol: TCP
      port: 5432
