apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: pvc-back-end1
  containers:
  - name: mongo
    image: mongo:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 27017
    volumeMounts:
      - name: storage
        mountPath: /data/db
