# Empty file. Use this to define the new StorageClass
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc1
provisioner: k8s.io/minikube-hostpath    
allowVolumeExpansion: true
volumeBindingMode: Immediate
reclaimPolicy: Retain
